name: CI - FastAPI Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi "uvicorn[standard]" black flake8 pytest

      - name: Check code formatting (Black)
        run: |
          black --check .

      - name: Lint with Flake8
        run: |
          flake8 app --max-line-length=100 --ignore=E203,W503

      - name: Run tests with Pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q
